steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:latest"
    args:
      [
        "compute",
        "url-maps",
        "invalidate-cdn-cache",
        "resume-lb",
        "--path",
        '"/*"',
      ]

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["rsync", "-x", '\.git.*', ".", "gs://jamesmskelsey-resume"]
